2020-03-09 22:49:03,502 [INFO   ] [APP] autotrader started with arguments={run.py}
2020-03-09 22:49:03,503 [INFO   ] [APP] configuration={"Execution":{"Host":"127.0.0.1","Port":12345},"Information":{"AllowBroadcast":false,"Interface":"0.0.0.0","ListenAddress":"239.255.1.1","Port":12346},"TeamName":"TraderOne","Secret":"secret"}
2020-03-09 22:49:23,121 [ERROR  ] [asyncio] Fatal error: protocol.data_received() call failed.
protocol: <autotrader.AutoTrader object at 0x7f44bec1cc10>
transport: <_SelectorSocketTransport fd=18 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/home/saze/anaconda3/lib/python3.7/asyncio/selector_events.py", line 816, in _read_ready__data_received
    self._protocol.data_received(data)
  File "/home/saze/Documents/competition/ready_trader_one/ready_trader_one/base_auto_trader.py", line 67, in data_received
    self.on_order_status_message(*ORDER_STATUS_MESSAGE.unpack_from(self._data, upto + HEADER_SIZE))
  File "/home/saze/Documents/competition/ready_trader_one/autotrader.py", line 184, in on_order_status_message
    self.send_amend_order(client_order_id, remaining_volume * 1.1)
  File "/home/saze/Documents/competition/ready_trader_one/ready_trader_one/base_auto_trader.py", line 151, in send_amend_order
    AMEND_MESSAGE.pack_into(self.amend_message, HEADER_SIZE, client_order_id, volume)
struct.error: required argument is not an integer
2020-03-09 22:49:23,121 [ERROR  ] [TRADER] lost connection on execution channel:
Traceback (most recent call last):
  File "/home/saze/anaconda3/lib/python3.7/asyncio/selector_events.py", line 816, in _read_ready__data_received
    self._protocol.data_received(data)
  File "/home/saze/Documents/competition/ready_trader_one/ready_trader_one/base_auto_trader.py", line 67, in data_received
    self.on_order_status_message(*ORDER_STATUS_MESSAGE.unpack_from(self._data, upto + HEADER_SIZE))
  File "/home/saze/Documents/competition/ready_trader_one/autotrader.py", line 184, in on_order_status_message
    self.send_amend_order(client_order_id, remaining_volume * 1.1)
  File "/home/saze/Documents/competition/ready_trader_one/ready_trader_one/base_auto_trader.py", line 151, in send_amend_order
    AMEND_MESSAGE.pack_into(self.amend_message, HEADER_SIZE, client_order_id, volume)
struct.error: required argument is not an integer
2020-03-09 22:49:23,121 [INFO   ] [APP] closing event loop
